version: '2.4'

services:
  client:
    container_name: client
    environment:
      ADDR: "server:5000"
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: client
    depends_on:
      server:
        condition: service_started

  server:
    container_name:   server
    environment:
      PORT: "5000"
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint:   server