version: "3"

tasks:
  run:
    cmds:
      - docker-compose -f docker-compose.yml down -v
      - docker-compose -f docker-compose.yml build
      - docker-compose -f docker-compose.yml up -d server client
      - docker-compose -f docker-compose.yml logs -f client
