package quotes

var Quotes = []string{
	"1. Never let your best friends get lonely, keep disturbing them.",
	"2. Sometimes I wish I was an octopus, so I could slap eight people at once.",
	"3. If Cinderella’s shoe fit perfectly, then why did it fall off?",
	"4. If you’re hotter than me, then that means I’m cooler than you.",
	"5. My wallet is like an onion, opening it makes me cry.",
	"6. My goal this weekend is to move, just enough so people don’t think I’m dead.",
	"7. Lazy people fact #2347827309018287. You were too lazy to read that number.",
	"8. Friends buy you food.Best friends eat your food.",
	"9. Papercut: A tree’s final moment of revenge.",
	"10. Common sense is like deodorant, those who need it the most never use it.",
	"11. I don’t need a hair stylist, my pillow gives me a new hairstyle every morning.",
	"12. Life always offers you a second chance.It’s called tomorrow.",
	"13. My six pack is protected by a layer of fat.",
	"14. When nothing is going right, go left.",
	"15. If you have crazy friends you have everything you’ll ever need.",
	"16. Silence is golden, unless you have kids, then silence is just plain suspicious.",
	"17. I’m not running away from hard work, I’m too lazy to run.",
	"18. Don’t make me laugh, I’m trying to be mad at you.",
	"19. If I won the award for laziness, I would send somebody to pick it up for me.",
	"20. Maybe if we tell people the brain is an app, they’ll start using it.",
	"21. My bed is a magical place where I suddenly remember everything I forgot to do.",
	"22. A best friend is like a four leaf clover, hard to find, lucky to have.",
	"23. Some people are like clouds.When they go away, it’s a brighter day.",
	"24. At night, I can’t fall asleep.In the morning, I can’t get up.",
	"25. Seeing a spider in my room isn’t scary.It’s scary when it disappears.",
	"26. If we shouldn’t eat at night, why is there a light in the fridge?",
	"26. They say ‘don’t try this at home’ so I’m coming over to your house to try it.",
	"27. When you fall, I will be there to catch you with love.Sincerely, the floor.",
	"28. I could agree with you, but then we’d both be wrong.",
	"29. I didn’t fall, I’m just spending some quality time with the floor.",
	"30. Lottery: a tax on people who are bad at math.",
	"31. IRS: We’ve got what it takes to take what you have got.",
	"32. What happens to a frog’s car when it breaks down? It gets toad away.",
	"33. Why was six scared of seven? Because seven “ate” nine.",
	"34. I only check my voicemail to get rid of the annoying little icon.",
	"35. My windows aren’t dirty, my dog is painting.",
	"36. No matter how bad it gets, I’m always rich when I go to the dollar store.",
	"37. Today, I laughed until my abs started hurting, so I can skip the gym.",
	"38. I know that I am intelligent, because I know that I know nothing.– Socrates",
	"39. I don’t suffer from insanity.I enjoy every minute of it.",
	"40. I said yes, which turned out to be the right answer.– Pat Sajak",
	"41. The only power you have is the word ‘no’.– Frances McDormand",
	"42. Art doesn’t transform.It just plain forms.– Roy Lichtenstein",
	"43. I said “no” to drugs, but they just wouldn’t listen.",
	"44. Every day is a gift, that’s why they call it the present.",
	"45. I believe we should all pay our tax bill with a smile.I tried, but they wanted cash.",
	"46. Why can’t you play cards on a small boat? Because someone is always sitting on the deck.",
	"47. Of course, I talk to myself, sometimes I need expert advice.",
	"48. Yes, of course, I am athletic, I surf the Internet every day.",
	"49. My silence spoke a thousand words, but you never heard them.",
	"50. I really should do something with my life, maybe tomorrow.",
	"51. When the past comes knocking, don’t answer.It has nothing new to tell you.",
	"52. Waiting until the movie starts to eat your popcorn, hardest thing in the world.",
	"53. I love my job only when I’m on vacation.",
	"54. Always follow your heart, but remember to bring your brain along.",
	"55. It’s alright if you don’t agree with me, I can’t force you to be right.",
	"56. I solemnly swear that I am up to no good.",
	"57. If people are talking behind your back, be happy that you are the one in front.",
	"58. You wanna know who I’m in love with? Read the first word again.",
	"59. I’m not arguing, I’m just telling you why you’re wrong.",
	"60. Be yourself; everyone else is already taken.",
	"61. I always carry a knife in my purse, just in case we’re having cake.",
	"62. I am on a seafood diet.I see food, and I eat it.",
	"63. I wonder how police on bikes arrest people.‘Alright, get in the basket.’",
	"64. The future is shaped by your dreams, so stop wasting time and go to sleep.",
	"65. If Monday had a face, I would punch it.",
	"66. A balanced diet means a cupcake in each hand.",
	"67. We all have baggage, find someone who loves you enough to help you unpack.",
	"68. My house was clean yesterday, sorry you missed it.",
	"69. When life closes a door, just open it again.It’s a door, that’s how they work.",
	"70. I don’t know how to act my age because I’ve never been this old before.",
	"71. A mind is like a parachute.It doesn’t work if it is not open.",
	"72. Relax, it’s the weekend, just don’t blink or it will be all over.",
	"73. The only relationship I have is with my Wifi.We have a connection.",
	"74. All my life I thought air was free, until I bought a bag of chips.",
	"75. The great pleasure in life is doing what people say you cannot do.– Walter Bagehot",
	"76. Doing nothing is hard, you never know when you’re done.",
	"77. We are going to be best friends forever, besides you already know too much.",
	"78. Square box, round pizza, triangle slices, now that’s confusing.",
	"79. Sorry, I didn’t pick up my phone, I got carried away dancing to the ringtone.",
	"80. You know you are lazy when you get excited about canceling your plans.",
	"81. Don’t give up on your dreams so soon, sleep longer.",
	"82. I’m not lazy, I’m just very relaxed.",
	"83. Never ask a starfish for directions.",
	"84. I wonder, do we lazy people go to heaven or do they send someone to pick us up?",
	"85. I lost some weight once, but I found it again in the fridge.",
	"86. Yesterday I did nothing and today I’m finishing what I did yesterday.",
	"87. I’m not lazy, I’m on power saving mode.",
	"88. If only common sense were more common.",
	"89. Do you believe in love at first sight, or should I walk by again?",
	"90. Stop texting me in the middle of texting you, now I have to change my text.",
	"91. You can stop driving me crazy, I can walk from here.",
	"92. Every weekend I do what I love most, absolutely nothing.",
	"93. Why do they call it beauty sleep when you wake up looking terrible?",
	"94. Everybody wants to go to heaven; but nobody wants to die.– Albert King",
	"95. Who says nothing is impossible? I’ve been doing nothing for years.",
	"96. I’m going to stand outside, so if anybody asks for me, I’m outstanding.",
	"97. I eat cake because it’s someone’s birthday somewhere today.",
	"98. Life’s biggest struggle: I need to pee, but I don’t want to get out of bed.",
	"99. Exercise? I thought you said extra fries.",
	"100. I did not trip and fall.I attacked the floor and I believe I am winning.",
	"101. People say you can’t live without love, but I think oxygen is more important.",
	"102. What do I do for a living? I breathe in and out.",
	"103. My boss is like a baby, screams and wakes me up every half hour.",
	"104. Give me a photo of you so I can show Santa what I want for Christmas.",
	"105. Why is Monday so far from Friday, and Friday so close to Monday?",
	"106. Never judge a book by its movie.",
	"107. The difference between stupidity and genius is that genius has its limits.– Albert Einstein",
	"108. Don’t worry, the spider is smaller than you.Yeah, so is a grenade.",
	"109. I hate Mondays, Tuesdays, Wednesdays, Thursdays, and half of Fridays.",
	"110. If you can’t remember my name, just say ‘chocolate’ and I’ll turn around..",
	"111. I may not know karate, but I know crazy and I’m not afraid to use it.",
	"112. I don’t like morning people, or mornings, or people.",
	"113. Why cry for someone when you can laugh next to someone else ?",
	"114. If you can’t laugh at your own problems, call me and I’ll laugh at them.",
	"115. Whenever I clean my closet I take a GPS with me, so I can find my way back.",
	"116. Nine out of ten people love chocolate, and the 10th person is always lying.",
	"117. If lying was a job some people would be billionaires.",
	"118. Cell phones these days keep getting thinner and smarter; people the opposite.",
	"119. I’m sorry that I’m not updating my Facebook status, my cat ate my mouse.",
	"120. I’m old enough to know better, but young enough to do it anyway.",
	"121. You can only be young once.But you can always be immature.– Dave Barry",
	"122. I know that I am stupid but when I look around me I feel a lot better.",
	"123. There’s life without Facebook and internet? Really? Send me the link.",
	"124. All you need is love.But a little chocolate now and then doesn’t hurt.– Charles M.Schulz",
	"125. I’m not weird, I’m just limited edition.",
	"126. Love your enemies.It makes them so damned mad.– P.D.East",
	"127. Don’t drink to forget me, you’ll end up seeing me double.",
	"128. It’s not important to win, it’s important to make the other guy lose.",
	"129. I am too lazy to be lazy.",
	"130. Maybe there are no excuses to be lazy, but I’m still going to keep looking.",
	"131. Life doesn’t have any hands, but it can sure give you a slap sometimes.",
	"132. Yes, officer, I saw the speed limit, I just didn’t see your car.",
	"133. Never take life seriously.Nobody gets out alive anyway.",
	"134. There are no stupid questions, just stupid people.",
	"135. I have a new hairstyle today, it’s called ‘I tried.’",
	"136. You can’t have everything, where would you put it? – Steven Alexander Wright",
	"137. I didn’t mean to push all your buttons, I was just looking for the mute button.",
	"138. I’m multitasking: I can listen, ignore and forget at the same time.",
	"139. Smile today, tomorrow could be worse.",
	"short funny quotes",
	"140. To the guy who created imaginary numbers in math: I hate you.",
	"141. Diet rule #1: If nobody sees you eating it, it doesn’t contain any calories.",
	"142. I never apologize.I’m sorry, but that’s just the way I am.",
	"143. I always dream of being a millionaire like my uncle.He’s dreaming too.",
	"144. When I was in high school I had two favorite subjects, lunch and recess.",
	"145. If you think nothing is impossible, try slamming a revolving door.",
	"146. He who wakes up early, yawns all day long.",
	"147. My imaginary friend thinks he has problems.",
	"148. Relationships these days start by pressing LIKE on her photo.",
	"149. If you don’t succeed at first, hide all evidence that you tried.",
	"150. Always remember you’re unique, just like everyone else.– Alison Boulter",
	"151. Forget the butterflies, I feel the entire zoo in my stomach when I’m with you.",
	"152. I tried looking at the bright side of life, but it hurt my eyes.",
	"153. Marriage is like a walk in the park, Jurassic Park.",
	"154. Sometimes when I close my eyes, I can’t see.",
	"155. I’m not here to judge, I’m just pointing out all the mistakes you’re making.",
	"156. Never let a fool kiss you, or a kiss fool you.",
	"157. He who laughs last didn’t get it.– Helen Giangregorio",
	"158. When our phones fall, we panic; but when our friends fall, we laugh.",
	"159. To make time fly, throw your watch out the window.",
	"160. The best things in life are free.The rest are too expensive.",
	"161. I don’t go crazy, I am crazy.I just go normal from time to time.",
	"short funny quotes",
	"162. Friends come and go, but enemies remain and build up.",
	"163. Never test how deep the water is with both feet.",
	"164. The man who smiles when things go wrong has thought of someone to blame it on.– Robert Bloch",
	"165. I’m so good at sleeping that I can do it with my eyes closed.",
	"166. Be careful when you follow the masses.Sometimes the ‘M’ is silent.",
	"167. With great power comes an even greater electricity bill.",
	"168. Life is always rocky when you’re a gem.",
	"169. If you die in an elevator, be sure to push the up button.– Sam Levenson",
	"170. I don’t need anger management, you just need to stop making me angry.",
	"171. I put my phone in airplane mode, but it’s not flying.",
	"172. You’re born free, then you’re taxed to death.",
	"173. I’ve made it from the bed to the couch.There’s no stopping me now.",
	"174. Your eyes water when you yawn, because you miss your bed and it makes you sad.",
	"175. Pleasing everyone, that’s impossible.Making everyone angry, piece of cake.",
	"176. Whoever said great things come in small packages hasn’t seen my big screen TV.",
	"177. I now pronounce you man and wife, you may now change your Facebook status.",
	"178. Whenever I am sad I go to my favorite place, the fridge.",
	"179. Those who snore always fall asleep first.",
	"180. The chains on my mood swing just snapped.Run.",
	"181. My diet for today: 1% food, 99% Halloween candy.",
	"182. Home: Where I can look ugly and not care.",
	"183. On Mercury, a day lasts 1, 408 hours.Just like every Monday does on Earth.",
	"184. Our toaster has two settings: too soon or too late.– Sam Levenson",
	"185. Today I was a hero.I rescued some beer that was trapped in a bottle.",
	"186. You never run out of things that can go wrong.– Edward A.Murphy",
	"187. I wasn’t mad, but now that you asked me 7 times if I’m mad..yes, I’m mad!",
	"188. Hmmm, this text message is a little too harsh, I’ll add ‘LOL’ at the end.",
	"189. Gravitation cannot be held responsible for people falling in love.– Albert Einstein",
	"190. Never go to a doctor whose office plants have died.– Erma Bombeck",
	"191. If nothing is impossible is it possible for something to be impossible?",
	"192. Smiles are contagious, be a carrier.",
	"193. Life is like a very long TV show, without a remote control.",
	"194. A bald spot is like a lie, the bigger it gets the harder it is to cover it up.",
	"195. I’m in desperate need of a 6-month vacation, twice a year.",
	"196. I love my computer because all my friends live inside it.",
	"197. My wife and I were happy for 20 years, then we met.– Rodney Dangerfield",
	"198. God heals, and the doctor takes the fees.– Benjamin Franklin",
	"199. Remember: Don’t Insult the Alligator till after you cross the river.",
	"200. Bowling Alley: Please be quiet.We need to hear a pin drop.",
	"201. Car Dealership: The best way to get back on your feet, miss a car payment.",
	"202. Are these genes in your jeans or are you just happy to see me?",
	"203. After Monday and Tuesday, even the calendar says W T F.",
	"204. What did one ocean say to the other ocean? Nothing, they just waved.",
	"205. The dyslexic devil worshipper sold his soul to Santa.",
	"206. Did you hear about the kidnapping at school? It’s okay, he woke up.",
	"207. What is the difference between snowmen and snowwomen? Snowballs.",
	"208. Why couldn’t the leopard play hide and seek? Because he was always spotted.",
	"209. What starts with E, ends with E, and has only 1 letter in it?  Envelope.",
	"210. How do you count cows? With a cowculator.",
	"211. How do astronomers organize a party? They planet.",
	"212. Why did the can crusher quit his job? Because it was soda pressing.",
	"213. I wish my wallet came with free refills.",
	"214. An apple a day keeps anyone a way, if you throw it hard enough.",
	"215. My room is like the Bermuda triangle, stuff goes in and is never seen again.",
	"216. It may look like I’m doing nothing, but in my head, I’m quite busy.",
	"217. Be strong, I whispered to my WiFi signal.",
	"218. You never know what you have, until you clean your closet.",
	"219. I enjoy taking long romantic walks, to the fridge.",
	"220. ‘Revenge’ sounds so mean, that’s why I prefer to call it ‘Returning the favor.’",
	"221. If everyone knew what I was thinking, I would get punched in the face a lot.",
	"222. I just wanted you to know that somebody cares.Not me, but somebody does.",
	"223. Don’t worry if plan A fails, there are 25 more letters in the alphabet.",
	"224. For the best seat in the house, you’ll have to move the dog.",
	"225. Having a smoking section in a restaurant is like having a peeing section in a pool.– Bill Murray",
	"226. As long as there are tests, there will be prayer in schools.",
	"227. You kill vegetarian vampires with a steak to the heart.",
	"228. A computer once beat me at chess, but it was no match for me at kickboxing.",
	"229. I asked my North Korean friend how it was there, he said he couldn’t complain.",
	"230. If you want to catch a squirrel just climb a tree and act like a nut.",
	"231. I haven’t talked to my wife in three weeks.I didn’t want to interrupt her.",
	"232. Not saying I hate you, but if your face was on fire and I had a glass of water, I’d drink it.",
	"233. I used to have winter fat but now I have spring rolls.",
	"234. Love may be blind, but marriage is a real eye-opener.",
	"235. Pampered cows produce spoiled milk.",
	"236. I heard a great joke about amnesia but I forgot it.",
	"237. Learn sign language, it’s very handy.",
	"238. Thank God I’m an atheist.",
	"239. The biggest critics of my books are the people who never read them.– Jackie Collins",
	"240. To err is human, but to really foul things up you need a computer.– Paul Ehrlich",
	"241. Man invented language to satisfy his deep need to complain.– Lily Tomlin",
	"242. Women and cats will do as they please, and men and dogs should relax and get used to the idea.– Robert",
	"243. If you want your children to listen, try talking softly to someone else.– Ann Landers",
	"244. A committee is a group that keeps the minutes and loses hours.– Milton Berle",
	"245. If at first, you don’t succeed, so much for skydiving.– Henny Youngman",
	"246. If you think women are the weaker sex, try pulling the blanket back to your side.– Stuart Turner",
	"247. I tell you what always catches my eye.Short people with an umbrella.– Gary Delaney",
	"248. I have Alzheimer’s bulimia, first I eat everything in sight and then I forget to puke.– Cindy from Mar",
	"249. No matter how bad it gets I’m always rich when I go to the dollar store.",
	"250. Wouldn’t exercise be more fun if calories screamed while you burned them? – Bill Murray",
	"251. I intend to live forever.So far, so good.– Steven Wright",
	"252. Happiness is having a large, loving, caring, close-knit family in another city.– George Burns",
	"253. First, the doctor told me the good news: I was going to have a disease named after me.– Steve Martin",
	"254. Honolulu, it’s got everything.Sand for the children, sun for the wife, sharks for the wife’s mother.",
	"255. I live in a neighborhood so bad that you can get shot while getting shot.– Chris Rock",
	"256. My legs are so sore from the gym that I almost couldn’t walk to the donut shop.– Bill Murray",
	"257. I bet giraffes don’t even know what farts smell like.– Bill Murray",
	"258. A bargain is something you don’t need at a price you can’t resist.– Franklin Jones",
	"259. I didn’t give you the finger, you earned it.– Bill Murray",
	"260. The early bird catches the worm, eats more and dies sooner.– Czech proverb",
	"261. If you steal from one author, it’s plagiarism; if you steal from many, it’s research.– Wilson Mizner",
	"262. If you think nobody cares if you’re alive, try missing a couple of car payments.– Flip Wilson",
	"263. My dream job would be the Karma delivery service.– Bill Murray",
	"264. Why do men find it difficult to make eye contact? Breasts don’t have eyes.",
	"265. Why is the man who invests all your money called a broker?",
	"266. What do you call a bear with no teeth? A gummy bear.",
	"267. Can February march? No, but April may.",
	"268. What do computers eat for a snack? Microchips.",
	"269. Why can’t you trust an atom? Because they make up everything.",
	"270. What is the tallest building in the entire world? The library, because it has so many stories.",
	"271. What’s the difference between a guitar and a fish? You can tune a guitar, but you can’t tuna fish.",
	"272. Why did the school kids eat their homework? Because their teacher told them it was a piece of cake.",
	"273. What did the blanket say when it fell off the bed? ‘Oh sheet!’",
	"274. Whoever invented knock knock jokes should get a no bell prize.",
	"275. What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
	"276. Why is England the wettest country? Because so many kings and queens have been reigning there.",
	"277. How do trees access the internet? They log in.",
	"278. What do you get when you cross a fish and an elephant? Swimming trunks.",
	"279. What is Mozart doing right now? Decomposing.",
}
